import js from "@eslint/js";
import ts from "typescript-eslint";
import svelte from "eslint-plugin-svelte";
import globals from "globals";

export default ts.config(
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs["flat/recommended"],
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    files: ["**/*.svelte"],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
      },
    },
  },
  {
    files: ["**/*.svelte.ts"],
    languageOptions: {
      parser: ts.parser,
    },
  },
  {
    // Keep Tauri-specific APIs encapsulated behind src/lib/platform/tauri/**.
    // Components and stores must depend on $lib/platform, not @tauri-apps/*
    // directly, so the same codebase can build for web (W4+).
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@tauri-apps/*"],
              message:
                "Import Tauri APIs only inside src/lib/platform/tauri/**. Components should use $lib/platform.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/lib/platform/tauri/**"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  {
    ignores: [
      "build/",
      ".svelte-kit/",
      "node_modules/",
      "src-tauri/",
      "target/",
      // wasm-pack output; regenerated by `pnpm build:wasm` and gitignored.
      "src/lib/wasm/",
    ],
  }
);
